### ISSUE TITLE
Worked once, kinda

### ISSUE THREAD

**Issue by CobreDev** [rensbreur/mouseplague#1]
I'm running macOS 10.15.4 on a 2012 MacBook Air along with a USB mouse.
I got this to build several times, but only one time have I gotten two cursors working, and the second cursor wasn't working right. It would act almost like the mouse was backwards, but it would do that no matter which way I held the mouse. All the other times I've tried, I haven't been able to get two cursors, and the USB mouse and the trackpad control the same cursor. I've tried cleaning the project folder and plugging the mouse and plugging it back in. Any ideas?

**Comment by rensbreur** [comment]
Thank you for taking the time to report this. The data sent from the mouse over usb was not interpreted correctly for a number of devices. I have just made some changes to the way this works, which I hope fixes the particular issue that the mouse seems to operate backwards.
As for the other issues you describe, let me get back on these later, but it is valuable feedback.
